### ISSUE TITLE
[BUG] Profile Viewer Bugs, Options show that they are still on when off.

### ISSUE THREAD

**Issue by Official-Darkn** [schnensch0/zelk#1]
**Describe the bug**
Options in the theme toggler menu or anything else is kind of broken, like when turning off an option it stays blue (it's a problem since it can confuse people to think that it's still on.)
Another bug is that when clicking on a profile, their profile banner is gone, notes are gone, and when viewing the profile, the entire top bar just looks weird.

**To Reproduce**
1. Enable Zelk.
2. Click on settings that has options to enable shit to see the on/off issue.
3. View a profile.

**Expected behavior**
I thought that it was suppose to just work normally, where the buttons would turn gray when off and profiles wouldn't be broken lol.

**Screenshots**
https://i.imgur.com/eMHHCcZ.png
https://i.imgur.com/Hrou54S.png
https://i.imgur.com/uTePlQp.png

**Setup**
 - OS: Windows 10 v21H1
 - Client Mod: Powercord v2 (f876037)
 - Release Channel: Discord Canary 87635 (0e8723d)
 - Other enabled Themes: Better Badges | BetterComfy | Discolored | Pop! | Settings Icons 
 - Other enabled Plugins: Majority of Default Powecord Plugins | Theme Toggler | bdCompact

**Comment by schnensch0** [comment]
Fixed the switches and the banners are still there, they're just the same color as the rest of the profile. If you thinks it's confusing to people I can make it optional, same for notes

**Comment by schnensch0** [comment]
fixed it. the banners aren't gone, they're just the same color as the rest of the profile. to re-enable notes put this `.note-1MiCN7 textarea, .note-367eZJ {
  display: unset !important;
}` in your quick css
