### ISSUE TITLE
[HELP] Is it normal for the emote icon to not follow the theme color scheme?

### ISSUE THREAD

**Issue by Minibus93** [schnensch0/zelk#10]
**What's your problem**
I'd like to know if the emote icon in the box where one writes messages is it supposed to follow the theme color scheme or not

**Additional context**
![Immagine](https://user-images.githubusercontent.com/73554423/126197906-7a626b75-623e-43ca-a86b-8b74c7a12968.png)

Adding screenshot for clarity, emote menu icon is gray and different compared to the others

**Comment by schnensch0** [comment]
Known issue. It's not a svg and changes on hover, so it's hard to color. I'll change it to a static one.

**Comment by Minibus93** [comment]
Thank you for the info! 

Great theme btw!

Going to close the issue :D

**Comment by schnensch0** [comment]
done
