### ISSUE TITLE
[BUG] Channel list not rounded at the bottom

### ISSUE THREAD

**Issue by Mobmaker55** [schnensch0/zelk#11]
**Describe the bug**
The bottom corners of the channel list is not rounded, and is instead square?

**To Reproduce**
1. Look at the bottom left corner of Discord.

**Screenshots**
![image](https://user-images.githubusercontent.com/45888585/126552739-3726bf6b-0a71-4f11-9a02-ef724b5d67d0.png)

**Setup**
 - OS: Windows 10 (20H2 or 21H1)
 - Client Mod: PowerCord
 - Release Channel: Canary 90725
 - Enabled Themes: Zelk 1.2
 - Enabled Plugins: Defaults + Theme Toggler

**Comment by Official-Darkn** [comment]
Yeah this happened to me but I couldn't really explain it well lol.

**Comment by schnensch0** [comment]
fixed
