### ISSUE TITLE
[BUG] Full-screen profile "About Me" has messed up margin

### ISSUE THREAD

**Issue by Mobmaker55** [schnensch0/zelk#12]
**Describe the bug**
The margins for the "About Me" box in the full-screen profile makes text clip.

**To Reproduce**
1. Right-click on someone, and then click "Profile".

**Screenshots**
Full-Screen
![image](https://user-images.githubusercontent.com/45888585/126663944-9ca3cebe-52ee-4eb3-a11d-ad20260f3bbe.png)

Windowed
![image](https://user-images.githubusercontent.com/45888585/126664009-51e8c167-6c3f-41a4-92b0-1bc2e70b27c4.png)

**Setup**
 - OS: Windows 10
 - Client Mod: Powercord
 - Release Channel: Canary (identical to my last issue idk)
 - Enabled Themes: Zelk 1.2
 - Enabled Plugins: Theme Toggler (needed to toggle themes)

**Comment by schnensch0** [comment]
I can't reproduce this. Do you have any Quick CSS snippets? And could you send a screenshot of the entire modal?

**Comment by Mobmaker55** [comment]
I don't have any Quick CSS snippets, however, I did re-enable scroll bars, if that's a problem.
![image](https://user-images.githubusercontent.com/45888585/127781632-5f02bf2c-10eb-4255-9911-795e22a64f9d.png)

**Comment by schnensch0** [comment]
Is it still an issue? Could you show me the associated styles in the dev tools?

**Comment by Mobmaker55** [comment]
Yes, I am still having this issue-- and it is persistent on all OSes and installs, not just Windows ( I tested on my POP!_OS 20.04 laptop)
![image](https://user-images.githubusercontent.com/45888585/128763535-13bffcb6-8c50-465e-9b76-e2d7fb7da942.png)

**Comment by schnensch0** [comment]
Doesn't happen to me on Windows and neither on POP!_OS 21.04.
1. Is it like this on all profiles with an about me?
2. Could you screenshot the `userInfoSection-q_35fn` styles in the dev tools?
3. What happens if you untick `display: none` on the `userInfoSectionHeader-3TYk6R`?

**Comment by Mobmaker55** [comment]
1. Yes, this is on all profiles with an about me.
2. ![image](https://user-images.githubusercontent.com/45888585/128964305-7c0fed85-8cd4-4708-bcc2-70c174765c7a.png)
3. Unticking that partially solved it, unticking `margin-top: -20px` on `userInfoSection-2_35fn` also helped.
(the `display: none` just removes "about me" and "note")

**Comment by schnensch0** [comment]
New approach in https://github.com/schnensch0/zelk/commit/e52f238a6780226e7ad76f52511f8fad38b06b50. Let me know if this fixed it.
