### ISSUE TITLE
[BUG] Replace the Icons for Settings and such with the one from snappercord's repo.

### ISSUE THREAD

**Issue by Official-Darkn** [schnensch0/zelk#13]
**Describe the bug**
Basically when using the default settings icons from downloading Zelk, the majority of icons are bugged, like some of them showing the default powercord logo for Spotify, Theme Toggler, etc.

Because of this, the icons should just be switched to the one from the snappercord repo. Plus it's a very simple fix to implement, just go to zelk.css, and replace the settings icon link with the one from snappercord's repo.

**To Reproduce**
1. Download Powercord and install it.
2. Install Theme Toggler.
3. Install Zelk.
4. Look at the Settings Icons.

**Screenshots**
https://imgur.com/8y4wuqL

**Setup**
 - OS: [e.g. Windows]
 - Client Mod: [e.g. BetterDiscord]
 - Release Channel: [e.g. canary, stable]
 - Enabled Themes: Zelk - Amazing Activity Cards - Better Badges - Discolored 
 - Enabled Plugins: Default Powercord Plugins - BetterDiscord Plugins | These plugins do not affect the UI.

**Comment by schnensch0** [comment]
thought it was abandoned, but after the recent commits i'll revert it back to before https://github.com/schnensch0/zelk/commit/82d4e3a4c33a2d1b7981fe3de180b0fecc64ca53

**Comment by schnensch0** [comment]
done
