### ISSUE TITLE
[BUG] Friends menu is no longer themed after a canary update

### ISSUE THREAD

**Issue by proudmuslim-dev** [schnensch0/zelk#15]
**Describe the bug**
Friends menu is no longer themed after a canary update. No other themes are enabled.

**To Reproduce**
1. Open discord
2. View friends menu

**Screenshots**

![image](https://user-images.githubusercontent.com/69869443/128918799-0c5af827-b119-4479-8ce7-39f4526bdd6f.png)

**Setup**
 - OS: Arch Linux
 - Client Mod: Powercord
 - Release Channel: Canary
 - Enabled Themes: Zelk
 - Discord Language: English

**Comment by schnensch0** [comment]
What's your exact Canary version (e.g. Canary 93139 (11cd0f2))

**Comment by schnensch0** [comment]
Fine on my side. Does this happen with an unmodified version of Zelk too?

**Comment by proudmuslim-dev** [comment]
Issue fixed as of latest commit, thank you
