### ISSUE TITLE
Discord Palette Colors

### ISSUE THREAD

**Issue by LucidNyxx** [schnensch0/zelk#16]
I have been trying for a while to change the colors to the default Discord colors with this theme. But I have no luck. I was just wondering if anyone else got it down?

**Comment by schnensch0** [comment]
![zelkdiscord](https://user-images.githubusercontent.com/58988092/129339581-65a4b13f-fb70-47d4-998e-15a76cd916be.png)
Pretty much done. Would you prefer the toolbar icons like this or transparent?

**Comment by LucidNyxx** [comment]
That's perfect! Just like that. But what do you mean transparent?

**Comment by schnensch0** [comment]
nvm, add `@import url(https://raw.githack.com/schnensch0/zelk/main/colors/discord.css);` to your Quick/Custom CSS and let me know if you find some weird parts (very likely)

**Comment by LucidNyxx** [comment]
Okay, I will. Thanks! It looks good! But I'll let you know if I find any weird parts.
