### ISSUE TITLE
[BUG] Add to server button is not centered

### ISSUE THREAD

**Issue by duqaqon** [schnensch0/zelk#23]
**Describe the bug**
_Add to server_ is not centered

**To Reproduce**
1. Go to a bot that has **Add to server** enabled and you will see that it's not centered.

**Screenshots**
https://imgur.com/a/AKyK6HC

**Setup**
 - OS: **Windows 11 (Also tested on Kubuntu)**
 - Client Mod: **BetterDiscord**
 - Release Channel: **Canary**
 - Enabled Themes: **Zelk**
 - Enabled Plugins: **MessageLoggerV2, ShowHiddenChannels**
 - Custom CSS: **no**
 - Discord Language: **English (UK)**

**Comment by schnensch0** [comment]
fixed in next commit

**Comment by duqaqon** [comment]
Thank you!
