### ISSUE TITLE
[BUG]Gift icon in text bar gets colored on hover

### ISSUE THREAD

**Issue by Minibus93** [schnensch0/zelk#24]
**Describe the bug**
The gift icon gets coloted on hover, not following the static "style" of the other icons in the text bar 

**To Reproduce**
1. Open discord
2. Look at the textbar where you type messages
3. Hover on the gift icon

**Screenshots**
![Immagine](https://user-images.githubusercontent.com/73554423/146960742-09fa0d8e-5b84-4df3-87b8-45362e9ec55c.png)

**Setup**
 - OS: W10
 - Client Mod: GooseMod
 - Release Channel: Stable
 - Enabled Themes: Zelk (gray one)
 - Enabled Plugins: Fucklytics, Silent Typing, Quick Mentions, Nitro spoof
 - Custom CSS: yes only this line "@import url(https://raw.githack.com/schnensch0/zelk/main/colors/gray.css);"
 - Discord Language: italian

**Comment by schnensch0** [comment]
fixed
