### ISSUE TITLE
[BUG] Spoiler block is the same colour as the background

### ISSUE THREAD

**Issue by SiJiL82** [schnensch0/zelk#25]
**Describe the bug**
Marking text as a spoiler blocks it out, and the block is the same colour as the background making it impossible to see where spoiler text is.

**To Reproduce**
1. Mark some text as spoiler. 
2. Block should be visible to be clicked on. It can still be clicked on but is not visible.

**Screenshots**
Covered spoiler:
![image](https://user-images.githubusercontent.com/65114782/147135302-1c5498dd-0c5b-4fc3-9ac7-85823aeada88.png)
Uncovered:
![image](https://user-images.githubusercontent.com/65114782/147135351-632880e2-db46-4238-badf-61107d7b62b8.png)

**Setup**
 - OS: Same in Windows and Linux
 - Client Mod: BetterDiscord
 - Release Channel: stable
 - Custom CSS: no
 - Discord Language: English

**Comment by schnensch0** [comment]
hopefully fixed
