### ISSUE TITLE
Embed Colors in Messages from Bots missing

### ISSUE THREAD

**Issue by TheRedCmdCraft** [schnensch0/zelk#26]
**Describe the bug**
On Embeds from Bots are the Embed Color missing. 

**To Reproduce**
1. Enable Zelk Theme 
2. search for an Embed from a Bot
3. There is the Embed Color Missing

**Screenshots**
![grafik](https://user-images.githubusercontent.com/57496807/147562482-96d288c5-a794-42d6-923c-2adb0bb9b6fc.png)

**Setup**
 - OS: Windows 11
 - Client Mod: BetterDiscord 1.3.0
 - Release Channel: Stable 108924
 - Enabled Themes: Zelk
 - Enabled Plugins: 
 - Custom CSS: no
 - Discord Language: German

**Comment by EvilToasterDBU** [comment]
I think it's worth moving this code into variables like this:
![image](https://user-images.githubusercontent.com/15957247/147614492-eac7264d-a6e0-4cc6-ad23-bc823bbb48d1.png)

**Comment by schnensch0** [comment]
added a `--embed-color` variable, you'll be prompted to update as soon as it's approved
