### ISSUE TITLE
Send Message Bar is missing[BUG]

### ISSUE THREAD

**Issue by Kippenhof** [schnensch0/zelk#27]
**Describe the bug**
The Send Message bar in the User Left Click context menu is missing

**To Reproduce**
 
1. Go on any Server
2. Click on any user
3. You can't directly message them
  
Picture of the Zelk Theme
![grafik](https://user-images.githubusercontent.com/54744977/147581681-8e64ba18-6d2f-4aed-8b88-73b88a548d49.png)
 
![grafik](https://user-images.githubusercontent.com/54744977/147581806-6a408218-3a96-4378-8506-15ce75abb11c.png)
Picture of the normal Discord Theme (The bar is Present)

To get the Results i just enabled/disabled the Zelk theme
**Screenshots**
If possible add screenshots to help explain your problem.

**Setup**
 - OS: Windows 11 21H2
 - Client Mod: BetterDiscord
 - Release Channel: Stable
 - Enabled Themes: Zelk (Gray)
 - Enabled Plugins: /
 - Custom CSS: no
 - Discord Language: German

**Comment by EvilToasterDBU** [comment]
Just off parametr hiding "direct message box" in "VARIABLES" like this
![image](https://user-images.githubusercontent.com/15957247/147685991-bfa333d3-64e4-4e9d-aa56-bbbc5b73a48d.png)

**Comment by Kippenhof** [comment]
thx. why is it hidden by default lol
