### ISSUE TITLE
DISCORD THEME BROKEN

### ISSUE THREAD

**Issue by GrandWasTaken** [schnensch0/zelk#29]
**Describe the bug**
Most themes have been hit by this Discord change, please fix as soon as possible.

**To Reproduce**
1. Launch Discord
2. Go to Friend's list

**Setup**
 - OS: macOS
 - Client Mod: BetterDiscord
 - Release Channel: Stable
 - Enabled Themes: Zelk
 - Enabled Plugins:
 - Custom CSS: No
 - Discord Language: English

**Comment by KilluaYT** [comment]
ye, something is a bit weird
![image](https://user-images.githubusercontent.com/38096703/148929679-0f5ce1e8-139f-4fd8-acca-6d8afe2220d5.png)
there parts which are light-gray/idk

**Comment by Spiretail** [comment]
Sizing/scaling appears to be broken, with colour problems and highlighting as well.
![image](https://user-images.githubusercontent.com/41858193/148949448-c63ec4b7-36f8-4000-aeef-8462c925cb38.png)

**Comment by GrandWasTaken** [comment]
Hopefully @schnensch0 is active.

**Comment by abedaton** [comment]
Same problem here

**Comment by Minibus93** [comment]
This happens because discord pushed multiple class changes.

All discord themes are broken rn, including some plugins and other stuff. 

It's not only a zelk issue, we just have to wait

**Comment by GrandWasTaken** [comment]
> This happens because discord pushed multiple class changes.
> 
> 
> 
> All discord themes are broken rn, including some plugins and other stuff. 
> 
> 
> 
> It's not only a zelk issue, we just have to wait
> 
> 

The theme developer can fix it.

**Comment by BouncyBird** [comment]
Looks like the developer has addressed this problem.

From the Zelk Discord Server:

> as you might've noticed all discord themes got broken by a recent update.
i'm going to push a fix for zelk tomorrow. thank you for your patience.
if you can't wait a day you can use @BLZxRsBEAST fork (thanks a lot) by replacing `@import url(https://raw.githack.com/schnensch0/zelk/main/main.css);` with `@import url(https://raw.githack.com/Davr1/zelk/main/main.css);`.

**Comment by GrandWasTaken** [comment]
Well that's a relief.

**Comment by schnensch0** [comment]
out now
