### ISSUE TITLE
[HELP] No scrollbar visible?

### ISSUE THREAD

**Issue by Quinten0508** [schnensch0/zelk#3]
**Problem / Question**
There doesn't seem to be a scrollbar in any server so I can scroll up or down in channels to read earlier messages.
Same goes for the "search" menu (when you click on the search icon on the upper right to search a channel for words or sentences)

Screenshot of channel without scrollbar: https://prnt.sc/16rrmjn
Screenshot of all plugins installed: https://prnt.sc/16rs35o

Is there not supposed to be a scrollbar, or is it a visual issue?

**Comment by schnensch0** [comment]
By default there is no scrollbar. To enable them navigate to the Themes tab in your settings, click the edit button next to Zelk and replace none with unset after --scrollbars.

**Comment by Botspot** [comment]
@schnensch0, I don't see a way to change options for Zelk at all. Using ArmCord - GooseMod edition.

**Comment by wtquin** [comment]
You can navigate to your themes folder and open `/zelk/zelk.css` in your text editor of choice. Then, on line 19, you can change ` --scrollbars: none;` to ` --scrollbars: unset;`. Save the file, then disable & re-enable the theme or restart your discord client.

**Comment by Botspot** [comment]
> You can navigate to your themes folder and open `/zelk/zelk.css` in your text editor of choice. Then, on line 19, you can change ` --scrollbars: none;` to ` --scrollbars: unset;`. Save the file, then disable & re-enable the theme or restart your discord client.

I can't seem to find any folder by the name of "zelk" in my home folder at all. Any idea where it could be?
BTW, I did not manually download this theme, GooseMod had like this theme marketplace where I clicked a button to apply the theme. That might make a difference.

**Comment by wtquin** [comment]
I don't know where Goosemod stores its themes, you'd have to ask around. It's probably on their website/github/discord. 

The "install" button probably just downloads the theme and puts it in the correct folder for you, there's no black magic going on there.
