### ISSUE TITLE
[BUG] Student Hub section has CSS issues

### ISSUE THREAD

**Issue by itanne99** [schnensch0/zelk#30]
**Describe the bug**
The "Join Servers" text color is blended with the background of the :active state for the channel
The navbar for the server categories is not styled to follow the style of the theme

**To Reproduce**
1. Go to 'student hub' for university

**Screenshots**
Join Servers Text
![image](https://user-images.githubusercontent.com/20746427/153071181-4e6ad4d4-b933-4cee-9d65-3a0a73e48eac.png)

Navbar for server categories
![image](https://user-images.githubusercontent.com/20746427/153071307-5305b0a3-e599-41f5-871d-4246ff1dd50b.png)

**Setup**
 - OS: Windows
 - Client Mod: BetterDiscord
 - Release Channel: stable
 - Enabled Themes: zelk
 - Enabled Plugins: None
 - Custom CSS: Nothing extra besides zelk
 - Discord Language: English

**Comment by schnensch0** [comment]
can't reproduce because i don't have access to a student hub...
would be very kind of you if you could send me the relevant classes

**Comment by itanne99** [comment]
I'm not sure which css class will be useful so I sent the HTML code pertaining to the following sections

Student Hub Navbar HTML: [https://gist.github.com/itanne99/c453c79358cd8f0c581d5ac88058bab3](https://gist.github.com/itanne99/c453c79358cd8f0c581d5ac88058bab3)

Student Hub: [https://gist.github.com/itanne99/078a77d347680dcc246054c036e38ad7](https://gist.github.com/itanne99/078a77d347680dcc246054c036e38ad7)

**Comment by schnensch0** [comment]
could you paste this into your custom css and tell me if it works
```css
.tabBarItem-15vAXA {
  border-radius: var(--border-radius-2);
  padding: 5px 8px;
}
.selected-1-Z6gm .name-3Vmqxm {
  color: var(--interactive-selected);
}
```

**Comment by itanne99** [comment]
It's perfect! Nice job.

I also realized another issue but will make a new post about it
