### ISSUE TITLE
[BUG] Having too many threads on 1 channel causes render issues

### ISSUE THREAD

**Issue by favna** [schnensch0/zelk#34]
**Describe the bug**

We're doing some big cleanup in our bot project and opening a lot of threads on 1 channel for that. Just this morning I noticed some of the UI of threads overflowing when doing so:

**To Reproduce**
1. Create 2 channels atop one another
2. Create 10 separate threads in the top channel
3. **Have someone else, or an alt, ping you in multiple threads (at least 5 or so)**
3. Threads should overflow, obscuring the # symbol of the bottom channel.

**Screenshots**

![image](https://user-images.githubusercontent.com/4019718/153871808-1f35ed0f-219f-476b-a7de-da0e8f415536.png)

**Setup**
 - Zelk Version: 1.2.2
 - OS: Windows 10 (20H2, Build 19042.1466)
 - Client Mod: Better Discord
 - Release Channel: Stable
 - Enabled Themes: Zelk
 - Enabled Plugins:
   - BDFB
   - Better Media Player
   - BetterMessageLinks
   - BetterNfwTag
   - CallTimeCounter
   - CompleteTimestamps
   - CreationDate
   - Double Click To Edit
   - FileViewer
   - HideStreamPreview
   - ImageUtilities
   - JoinedAtDate
   - QuickMention
   - RemoveChatButtons
   - ShowBadgesInChat
   - StaffTag
   - WhoReacted
   - WriteUpperCase
   - ZeresPluginLibrary 
 - Custom CSS: No
 - Discord Language: en-GB

**Comment by favna** [comment]
It appears that I missed a reproduction step, being that I wasn't in full control of the reproduction before. Another requirement is to have pending pings in the threads. Here is a video recording of where the issue becomes clear as it plays. Note that I have disabled *all* plugins before recording this:



https://user-images.githubusercontent.com/4019718/153928188-acab51fd-45c6-412f-9f5f-f9302755b785.mp4


The problem appears to be related to that threads with pings are thinner than those without.

**Comment by schnensch0** [comment]
fixed
