### ISSUE TITLE
How do i make my theme gray dark

### ISSUE THREAD

**Issue by khaledmoayad** [schnensch0/zelk#35]
idk where else to put this so sry i had to come to issues, maybe add settings to the themes to change modes easily

**Comment by TPO100Cofficial** [comment]
oh!
the themes do actually, just not graphically
look in your user settings, go to themes, find zelk and click the pencil button. that, or go to your file manager, find your betterdiscord themes folder, and open zelk.theme.css.
remove the css /*comment*/ brackets (slashes and asterisks) from the url for the gray theme and add them to the blue theme/whatever you were using before

```css
/*@import url(https://raw.githack.com/schnensch0/zelk/main/colors/gray.css);*/
@import url(https://raw.githack.com/schnensch0/zelk/main/colors/blue.css);
```
becomes
```css
@import url(https://raw.githack.com/schnensch0/zelk/main/colors/gray.css);
/*@import url(https://raw.githack.com/schnensch0/zelk/main/colors/blue.css);*/

```

**Comment by khaledmoayad** [comment]
That's exactly what I needed. Thanks! closing this now.
