### ISSUE TITLE
[BUG] Badges are formatted weirdly

### ISSUE THREAD

**Issue by axisiscool** [schnensch0/zelk#37]
**Describe the bug**
When viewing a user's profile, the badges are padded too much on the left and sometimes cause overlap with the user's username or cause their username to go partially to the next line.

**To Reproduce**
1. Click on a user's profile (especially someone with a lot of badges) and observe.

**Screenshots**
![DiscordCanary_tuQ7TM1FL1](https://user-images.githubusercontent.com/54381371/163751391-4e6ce8e9-9396-4701-93ae-63bd73223ce2.png)
![DiscordCanary_pqIj2nnLZJ](https://user-images.githubusercontent.com/54381371/163751396-6104a207-aab2-4366-b80c-4f6ac53044a5.png)
![DiscordCanary_jiOtu4ZqT0](https://user-images.githubusercontent.com/54381371/163751536-116a10da-b093-4e44-946e-210506a7b455.png)

**Setup**
 - OS: **Windows**
 - Client Mod: **Powercord**
 - Release Channel: **canary**
 - Enabled Themes: **zelk**
 - Enabled Plugins: **Spotify**
 - Custom CSS: **no**
 - Discord Language: **English (US)**

**Comment by Eejit43** [comment]
Can reproduce on Canary on macOS

**Comment by schnensch0** [comment]
fixed
