### ISSUE TITLE
[FEATURE REQUEST] About Me Section

### ISSUE THREAD

**Issue by tokiioKH** [schnensch0/zelk#4]
I am not sure if the theme has the updated about me section for userpopouts. It doesn't say "about me" when you click on the userpopouts. Also, some of the words are cut off on the about me section

**Comment by schnensch0** [comment]
The about me section is there, just the title is removed. E.g. here aaaaaaaa is the status and eeeeeeee is about me. Is this confusing to you? Should I add the title back?
![eeeeeeeeeee](https://user-images.githubusercontent.com/58988092/123505773-4738ab00-d661-11eb-9eb9-687772b87345.png)
And could you tell me where you're seeing words being cut off?

**Comment by tokiioKH** [comment]
Oh okay. Yeah, I think I just got confused because I didn't see the about me. 
![Discord_wD2NeuEc7W](https://user-images.githubusercontent.com/56203908/123507991-9b239f80-d621-11eb-9b0c-630807c43d68.png)
It's when you click on view profile.
