### ISSUE TITLE
[BUG] Profile Modal - Banners Rendered Properly

### ISSUE THREAD

**Issue by ytcalifax** [schnensch0/zelk#40]
## Describe the bug:
User's banners when viewing their profile is not aligned properly/does not cover the whole top of the modal.

## Steps to reproduce the behavior:

- Click any user
- Open their profile
- That's it

## Screenshots:
![image](https://user-images.githubusercontent.com/15365857/166126939-0ff3bbf1-c9f0-4c53-abb9-7341daefedf2.png)

## Setup:
OS: Windows 11 (22H2)
Client Mod: PowerCord
Release Channel: canary
Enabled Themes: zelk
Enabled Plugins: PinDMS, Report Messages, Unindent
Custom CSS: NO
Discord Language: English

**Comment by schnensch0** [comment]
still?

**Comment by ytcalifax** [comment]
It's fixed now. I properly see the banners.
