### ISSUE TITLE
[BUG] The profile information on the bottom left corner of Discord no longer fits w/ Zelk.

### ISSUE THREAD

**Issue by Official-Darkn** [schnensch0/zelk#5]
**Describe the bug**
Title describes it all.
Use Zelk, and look at the bottom left corner of Discord.
Both any plugin that goes with the profile information thingy and the thing itself no longer fits with Zelk.

**To Reproduce**
1. Install Powercord.
2. Get Theme Toggler & Zelk.
3. Look at the bottom left corner.

**Screenshots**
https://i.imgur.com/2MfGAZO.png
https://i.imgur.com/52mNtwg.png

**Setup**
 - OS: Windows 10 21H1 (OS Build 19043.1052)
 - Client Mod: Powercord.... unknown version.
 - Release Channel: Discord Canary 88877 (91ec52d)
 - Enabled Themes: Zelk 1.1.1 | Better Badges 1.2 | Discolored 1.0.0
 - Enabled Plugins: Default Powercord Plugins | BDFDB | BetterImageViewer | BlurNSFW | CopyRawMessage | CreationDate | GoogleTranslateOption | MessageLoggerV2 | MultiUploads | QuickDeleteMessages | bdCompact | Theme Toggler | Reacter

**Comment by schnensch0** [comment]
fixed it

**Comment by Official-Darkn** [comment]
Oh yeah and thanks for fixing it but on the bottom of it, it still has a square shape instead of a rounded shape.
https://i.imgur.com/YCfx8Qi.png
_very picky ik cri_

**Comment by schnensch0** [comment]
hmmm, not in my experience, where exactly is it (channel list, dms etc)?

**Comment by Official-Darkn** [comment]
> hmmm, not in my experience, where exactly is it (channel list, dms etc)?

both lol, going to a server, dm's, anywhere, it still has a square shape and such.
