### ISSUE TITLE
[BUG] Servers folders look improper when they are expanded.

### ISSUE THREAD

**Issue by Ziyph** [schnensch0/zelk#7]
**Describe the bug**
Server folders look improper when they are expanded.

**To Reproduce**
1. Expand a server folder.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/57063197/123980786-d0b4e980-d98f-11eb-9356-f39fb702a471.png)

**Setup**
 - OS: macOS
 - Client Mod: BetterDiscord
 - Release Channel: Stable
 - Enabled Themes: Zelk

**Comment by schnensch0** [comment]
known bug, pushed a fix rn
