### ISSUE TITLE
Scrollbars enabled?

### ISSUE THREAD

**Issue by mighelce** [schnensch0/zelk#8]
So, i wanted to now how can i turn the scrollbars on. It says none, and i don't know what to type to enable it. Nice theme man, i really like :D.

**Comment by FadelesSpade** [comment]
Discord > Settings > Themes > Zelk > Edit
![image](https://user-images.githubusercontent.com/42529233/124484628-a1c8ba00-dd79-11eb-85e7-2340096e73a8.png)
