### ISSUE TITLE
[BUG] GUI Transparency Interference

### ISSUE THREAD

**Issue by FadelesSpade** [schnensch0/zelk#9]
**Description**
Certain menus do not have filled background colors, thus resulting in a transparent background and interfering with the usability of the menus.

**Reproduction**
- Any menu that results from hovering. (Server names, settings, information about icon, etc).
- Server menu.

**Screenshots**
_Here are just a few_
![image](https://user-images.githubusercontent.com/42529233/124485063-2fa4a500-dd7a-11eb-8265-6b4e063f5e16.png)
![image](https://user-images.githubusercontent.com/42529233/124485092-38957680-dd7a-11eb-9078-9e90bdaee1a1.png)
![image](https://user-images.githubusercontent.com/42529233/124485164-4b0fb000-dd7a-11eb-81cb-59ad19df53d1.png)

**Setup**
 - OS: Windows
 - Client Mod: BetterDiscord
 - Release Channel: Stable
 - Enabled Themes: Zelk (Only)
 - Enabled Plugins: N/A

**Comment by schnensch0** [comment]
Not in my experience. Have you changed the --background-floating or --background-1 variables?

**Comment by FadelesSpade** [comment]
v1.1.1
It has been like this say day one. The only code changes are displaying the scrollbar and implementing split text that you gave me.
![image](https://user-images.githubusercontent.com/42529233/124486769-ed7c6300-dd7b-11eb-8d36-a789244359bc.png)

**Comment by schnensch0** [comment]
Try [downloading v1.2](https://betterdiscord.app/Download?id=300), you will have to re-enable scrollbars btw

**Comment by FadelesSpade** [comment]
I noticed your 1.2 push happened about 2 minutes before my issue report, unlucky as I would have just pulled it,

1.2 fixes the issue, closed.

**Comment by FadelesSpade** [comment]
I'm going to reopen this for the sake of not spamming you; we can close it shortly after.

Due to the split text implementation, my message prompt is looking cluttered. I'm only familiar with discord bots, not themes, so would you down to provide me the needed code to increase the chat lower cutoff?

![image](https://user-images.githubusercontent.com/42529233/124490700-6da4c780-dd80-11eb-9e2b-e65970326eb2.png)

The image and text are obviously hidden behind the message prompt, but the message background CSS is obviously not cutoff yet.

What's it going to take to make it look like so:
![image](https://user-images.githubusercontent.com/42529233/124491199-fde30c80-dd80-11eb-98cd-95e3351d3e54.png)

**Comment by schnensch0** [comment]
```css
.messagesWrapper-1sRNjr {margin-bottom: 8px;}
```
add some pixels if you'd like there to be a space
